"""Ⅲ. 시스템 분석서 5절 — 순서 다이어그램 8종 (코드 기준). 실행: python docs/report/figures/draw_sequences.py"""
from pathlib import Path

from seqdiag import Seq

HERE = Path(__file__).parent


def login():
    d = Seq("로그인", ["사용자", "시스템(앱)", "Google 인증", "Firebase Auth", "Firestore"])
    d.ret("시스템(앱)", "사용자", "로그인 화면 출력")
    d.msg("사용자", "시스템(앱)", "'Google로 계속하기' 클릭")
    d.msg("시스템(앱)", "Google 인증", "계정 선택·ID 토큰 요청 (Credential Manager)")
    d.ret("Google 인증", "시스템(앱)", "ID 토큰 전달")
    d.msg("시스템(앱)", "Firebase Auth", "signInWithCredential(ID 토큰)")
    d.ret("Firebase Auth", "시스템(앱)", "UID 반환")
    d.msg("시스템(앱)", "Firestore", "users/{uid} 조회")
    d.ret("Firestore", "시스템(앱)", "문서 반환 (onboardingCompleted)")
    d.frame("alt", "[문서 있음 · 온보딩 완료]")
    d.self_msg("시스템(앱)", "FCM 토큰 발급·저장")
    d.ret("시스템(앱)", "사용자", "메인 화면 이동 (모델 미설치 시 다운로드 화면 경유)")
    d.else_("[문서 없음 → 최초 로그인]")
    d.msg("시스템(앱)", "Firestore", "users/{uid} 생성 (onboardingCompleted=false)")
    d.ret("시스템(앱)", "사용자", "온보딩 화면 이동 (5.2)")
    d.else_("[인증 취소·실패 (E-1)]")
    d.ret("시스템(앱)", "사용자", "오류 메시지 출력, 로그인 화면 유지")
    d.end()
    return d.render(HERE / "seq_01_login.png")


def signup():
    d = Seq("회원가입 (최초 로그인 자동 가입 + 온보딩)", ["사용자", "시스템(앱)", "Firebase Auth", "Firestore"])
    d.msg("사용자", "시스템(앱)", "Google 로그인 완료 (5.1)")
    d.msg("시스템(앱)", "Firestore", "users/{uid} 조회")
    d.ret("Firestore", "시스템(앱)", "문서 없음")
    d.note("시스템(앱)", "별도 가입 입력 없음 —\nFirebase Auth 사용자는 인증 시 이미 생성됨")
    d.msg("시스템(앱)", "Firestore", "users/{uid} 생성 (onboardingCompleted=false)")
    d.ret("Firestore", "시스템(앱)", "저장 완료")
    d.ret("시스템(앱)", "사용자", "온보딩 화면 출력 (4단계 슬라이드)")
    d.frame("loop", "[슬라이드 1 → 4]")
    d.msg("사용자", "시스템(앱)", "다음 / 스와이프")
    d.end()
    d.msg("사용자", "시스템(앱)", "'시작하기' 클릭")
    d.msg("시스템(앱)", "Firestore", "users/{uid}.onboardingCompleted = true")
    d.ret("Firestore", "시스템(앱)", "갱신 완료")
    d.self_msg("시스템(앱)", "FCM 토큰 발급·저장")
    d.ret("시스템(앱)", "사용자", "메인 화면 이동")
    d.frame("alt", "[Firestore 조회·저장 실패 (E-2)]")
    d.ret("시스템(앱)", "사용자", "온보딩 화면으로 폴백 (재로그인 시 재조회)")
    d.end()
    return d.render(HERE / "seq_02_signup.png")


def withdraw():
    d = Seq("회원탈퇴 (구현 전제)", ["사용자", "시스템(앱)", "Firestore", "Room DB(로컬)", "Firebase Auth"])
    d.ret("시스템(앱)", "사용자", "마이페이지 출력")
    d.msg("사용자", "시스템(앱)", "'회원 탈퇴' 클릭")
    d.ret("시스템(앱)", "사용자", "비가역 안내 확인 다이얼로그")
    d.msg("사용자", "시스템(앱)", "확인")
    d.frame("loop", "[참여 중인 모든 방]")
    d.msg("시스템(앱)", "Firestore", "방 나가기 (5.7 트랜잭션)")
    d.end()
    d.msg("시스템(앱)", "Firestore", "users/{uid} + roomReads 삭제, FCM 토큰 제거")
    d.ret("Firestore", "시스템(앱)", "삭제 완료")
    d.msg("시스템(앱)", "Room DB(로컬)", "성향·후기·추천 결과 삭제")
    d.msg("시스템(앱)", "Firebase Auth", "currentUser.delete()")
    d.frame("alt", "[삭제 성공]")
    d.ret("Firebase Auth", "시스템(앱)", "삭제 완료")
    d.ret("시스템(앱)", "사용자", "탈퇴 완료, 로그인 화면 이동")
    d.else_("[최근 로그인 필요 (E-3)]")
    d.ret("Firebase Auth", "시스템(앱)", "requires-recent-login")
    d.msg("시스템(앱)", "Firebase Auth", "Google 재인증 후 delete() 재시도")
    d.end()
    return d.render(HERE / "seq_03_withdraw.png")


def create_room():
    d = Seq("채팅생성", ["사용자", "시스템(앱)", "Firestore"])
    d.ret("시스템(앱)", "사용자", "모임방 목록 화면 ('+' 버튼)")
    d.msg("사용자", "시스템(앱)", "방 이름 입력 후 생성 클릭")
    d.self_msg("시스템(앱)", "6자리 초대코드 생성")
    d.frame("loop", "[코드 중복이면 재생성]")
    d.msg("시스템(앱)", "Firestore", "inviteCodes/{code} 존재 확인")
    d.ret("Firestore", "시스템(앱)", "존재 여부")
    d.end()
    d.msg("시스템(앱)", "Firestore", "rooms 추가 (name, participantUids=[uid], createdAt, inviteCode)")
    d.msg("시스템(앱)", "Firestore", "inviteCodes/{code} = {roomId}")
    d.frame("alt", "[성공]")
    d.ret("Firestore", "시스템(앱)", "저장 완료 (roomId)")
    d.ret("시스템(앱)", "사용자", "채팅방 화면 이동 (상단 ⓘ로 초대코드 확인·복사)")
    d.else_("[실패: E-1 DB 저장 실패]")
    d.ret("Firestore", "시스템(앱)", "오류")
    d.ret("시스템(앱)", "사용자", "'채팅방 생성에 실패했습니다' 출력, 생성 화면 유지")
    d.end()
    return d.render(HERE / "seq_04_create.png")


def join_room():
    d = Seq("채팅참여 (초대코드 입장)", ["사용자", "시스템(앱)", "Firestore"])
    d.msg("사용자", "시스템(앱)", "'코드 입장' 선택, 6자리 초대코드 입력")
    d.self_msg("시스템(앱)", "형식 검증 (대문자·숫자 6자리)")
    d.frame("alt", "[형식 오류 (E-2)]")
    d.ret("시스템(앱)", "사용자", "형식 안내 메시지, 입력 화면 유지")
    d.else_("[형식 정상]")
    d.msg("시스템(앱)", "Firestore", "inviteCodes/{code} 조회")
    d.frame("alt", "[코드 존재]")
    d.ret("Firestore", "시스템(앱)", "roomId 반환")
    d.msg("시스템(앱)", "Firestore", "rooms/{roomId}.participantUids arrayUnion(uid)")
    d.ret("Firestore", "시스템(앱)", "갱신 완료")
    d.ret("시스템(앱)", "사용자", "채팅방 화면 이동")
    d.else_("[코드 없음·방 삭제됨 (E-3)]")
    d.ret("Firestore", "시스템(앱)", "문서 없음")
    d.ret("시스템(앱)", "사용자", "'존재하지 않는 초대코드입니다', 입력 화면 유지")
    d.end()
    d.end()
    return d.render(HERE / "seq_05_join.png")


def list_rooms():
    d = Seq("채팅조회 (목록 실시간 구독)", ["사용자", "시스템(앱)", "Firestore"])
    d.msg("사용자", "시스템(앱)", "모임방 목록 화면 진입")
    d.msg("시스템(앱)", "Firestore", "rooms where participantUids contains uid — Snapshot 구독")
    d.msg("시스템(앱)", "Firestore", "users/{uid}/roomReads 구독 (마지막 읽은 시각)")
    d.frame("alt", "[성공]")
    d.ret("Firestore", "시스템(앱)", "방 목록 (이름·마지막 메시지·시각)")
    d.self_msg("시스템(앱)", "안읽음 수 계산 (lastMessageTime > lastReadTime)")
    d.ret("시스템(앱)", "사용자", "목록 + 안읽음 뱃지 표시")
    d.frame("loop", "[변경 발생 시마다]")
    d.ret("Firestore", "시스템(앱)", "스냅샷 갱신")
    d.ret("시스템(앱)", "사용자", "목록 즉시 갱신")
    d.end()
    d.else_("[실패: E-4 DB 조회 실패]")
    d.ret("Firestore", "시스템(앱)", "오류")
    d.ret("시스템(앱)", "사용자", "빈 목록 + 오류 상태 표시")
    d.end()
    return d.render(HERE / "seq_06_list.png")


def leave_room():
    d = Seq("채팅삭제 (방 나가기 — 마지막 멤버 시 삭제)", ["사용자", "시스템(앱)", "Firestore"])
    d.msg("사용자", "시스템(앱)", "채팅방 메뉴 '방 나가기' 클릭")
    d.ret("시스템(앱)", "사용자", "확인 다이얼로그 ('마지막 멤버라면 방이 삭제됩니다')")
    d.msg("사용자", "시스템(앱)", "나가기 확인")
    d.msg("시스템(앱)", "Firestore", "트랜잭션: participantUids에서 uid 제거, 남은 인원 확정")
    d.frame("alt", "[남은 멤버 있음]")
    d.ret("Firestore", "시스템(앱)", "remaining > 0")
    d.ret("시스템(앱)", "사용자", "목록 화면 이동")
    d.else_("[내가 마지막 멤버]")
    d.ret("Firestore", "시스템(앱)", "remaining = 0")
    d.msg("시스템(앱)", "Firestore", "messages 하위 컬렉션 500건 단위 batch 삭제")
    d.msg("시스템(앱)", "Firestore", "inviteCodes/{code} 삭제")
    d.msg("시스템(앱)", "Firestore", "rooms/{roomId} 삭제")
    d.ret("시스템(앱)", "사용자", "목록 화면 이동")
    d.else_("[방이 이미 삭제됨 (E-5)]")
    d.ret("Firestore", "시스템(앱)", "문서 없음")
    d.ret("시스템(앱)", "사용자", "추가 처리 없이 목록 화면 이동")
    d.end()
    return d.render(HERE / "seq_07_leave.png")


def ai_analysis():
    P = ["사용자", "UI / ViewModel", "Orchestrator", "Gemma 4\n(온디바이스)", "PiiScrubber", "EmbeddingGemma\nRAG",
         "Room DB", "Functions 프록시", "Gemini", "외부 API\n(기상청·카카오)", "Guardrail ·\nReflection"]
    d = Seq("AI 분석 (UC-003)", P, x_step=3.1)
    d.frame("loop", "[Track 1 — 메시지 10개 누적마다, 백그라운드]")
    d.msg("UI / ViewModel", "Gemma 4\n(온디바이스)", "최근 15개 메시지 → compress() (constrained decoding)")
    d.ret("Gemma 4\n(온디바이스)", "UI / ViewModel", "record_status 툴콜 JSON")
    d.msg("UI / ViewModel", "Room DB", "방어적 파싱 → 직전 프로필과 병합 → user_status Upsert")
    d.end()
    d.msg("사용자", "UI / ViewModel", "'이야기 정리' 클릭")
    d.self_msg("UI / ViewModel", "진행 중 압축 완료 대기 (compressionJob.join)")
    d.msg("UI / ViewModel", "Room DB", "user_status 로드")
    d.msg("UI / ViewModel", "Orchestrator", "orchestrate(messages, userStatus)")
    d.msg("Orchestrator", "Gemma 4\n(온디바이스)", "summarizeForPrivacy(본문만)")
    d.ret("Gemma 4\n(온디바이스)", "Orchestrator", "익명화 요약 2~3문장")
    d.msg("Orchestrator", "PiiScrubber", "scrub(요약, 참가자 명단)")
    d.ret("PiiScrubber", "Orchestrator", "마스킹된 요약")
    d.msg("Orchestrator", "EmbeddingGemma\nRAG", "retrieve(요약, top3)")
    d.msg("EmbeddingGemma\nRAG", "Room DB", "feedback 벡터 코사인 검색")
    d.ret("EmbeddingGemma\nRAG", "Orchestrator", "관련 후기 (→ PiiScrubber 통과)")
    d.frame("loop", "[최대 3회 — Guardrail·Reflection 통과까지]")
    d.msg("Orchestrator", "Functions 프록시", "geminiGenerate(프롬프트+도구명세+응답스키마)")
    d.msg("Functions 프록시", "Gemini", "generateContent (키 부착)")
    d.frame("loop", "[Function Calling — 최대 8회 왕복]")
    d.ret("Gemini", "Orchestrator", "toolCall getWeather / searchPlace")
    d.msg("Orchestrator", "Functions 프록시", "weatherMidFcst / kakaoSearch")
    d.msg("Functions 프록시", "외부 API\n(기상청·카카오)", "기상청 중기예보 · 카카오 키워드 검색")
    d.ret("외부 API\n(기상청·카카오)", "Orchestrator", "도구 결과 (프록시 경유)")
    d.msg("Orchestrator", "Gemini", "functionResponse 주입 후 재추론 (프록시 경유)")
    d.end()
    d.ret("Gemini", "Orchestrator", "최종 JSON (요약·장소 2~3·활동·준비물)")
    d.msg("Orchestrator", "Guardrail ·\nReflection", "verify(장소명) · reflect(추천, 싫어요 제약)")
    d.msg("Guardrail ·\nReflection", "외부 API\n(기상청·카카오)", "카카오 로컬 실존 확인 (프록시 경유)")
    d.ret("Guardrail ·\nReflection", "Orchestrator", "OPEN/CLOSED/UNKNOWN · 위반 목록")
    d.frame("alt", "[CLOSED 또는 불호 위반]")
    d.self_msg("Orchestrator", "반려 사유 누적 → 다음 시도 (A-3)")
    d.else_("[통과]")
    d.self_msg("Orchestrator", "break — 검증 상태를 결과에 병합")
    d.end()
    d.end()
    d.ret("Orchestrator", "UI / ViewModel", "OrchestratorResult.Success(MeetingSummary)")
    d.msg("UI / ViewModel", "Room DB", "meeting_summary 저장, recommended_room 표시")
    d.ret("UI / ViewModel", "사용자", "AI 리포트 카드 표시 + 완료 푸시 알림")
    d.frame("opt", "[후기 — 리포트 화면 버튼 또는 재진입 팝업]")
    d.msg("사용자", "UI / ViewModel", "모임 후기 입력")
    d.msg("UI / ViewModel", "Room DB", "feedback 저장")
    d.msg("UI / ViewModel", "EmbeddingGemma\nRAG", "임베딩 인덱싱 (실패 시 앱 시작 때 재인덱싱)")
    d.end()
    return d.render(HERE / "seq_08_ai.png")


if __name__ == "__main__":
    for fn in (login, signup, withdraw, create_room, join_room, list_rooms, leave_room, ai_analysis):
        print("saved", fn())
